name: Flutter Quality Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  flutter-lint:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  

      - name: Set up Flutter
        uses: subosito/flutter-action@v2  
        with:
          flutter-version: 'stable'  

      - name: Install dependencies
        run: |
          flutter pub get  # Instala las dependencias del proyecto Flutter

      - name: Run Flutter analyze
        run: flutter analyze  

      - name: Run Flutter test
        run: flutter test 

      - name: Run Flutter format check
        run: flutter format --set-exit-if-changed . 
